version: "3.9"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - "gunicorn"
      - "django_diploma.wsgi:application"
      - "--bind"
      - "0.0.0.0:8000"
    expose:
      - 8000
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    volumes:
      - ./django_diploma/database:/app/database
      - static_volume:/app/static/

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static
    ports:
      - "1337:80"
    depends_on:
      - app
volumes:
  static_volume: