# Generated by Django 4.2.1 on 2023-05-22 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 21, 2, 51, 806888, tzinfo=datetime.timezone.utc), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 21, 2, 51, 808533, tzinfo=datetime.timezone.utc), verbose_name='date'),
        ),
    ]
