# Generated by Django 4.2.1 on 2023-05-22 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0002_alter_product_date_alter_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 21, 11, 14, 397011, tzinfo=datetime.timezone.utc), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 21, 11, 14, 398745, tzinfo=datetime.timezone.utc), verbose_name='date'),
        ),
    ]
