# Generated by Django 4.2.1 on 2023-05-31 17:35

from django.db import migrations, models
import django.db.models.deletion
import shop_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='fullName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=shop_api.models.profile_avatar_directory_path, verbose_name='avatar')),
                ('src', models.CharField(max_length=100)),
                ('alt', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_api.profile')),
            ],
            options={
                'verbose_name': 'avatar',
            },
        ),
    ]
