# Generated by Django 4.2.1 on 2023-05-31 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0007_remove_profile_avatar_profile_email_profile_fullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='user_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_api.avatar'),
        ),
    ]
