# Generated by Django 4.2.1 on 2023-05-31 18:08

from django.db import migrations, models
import django.db.models.deletion
import shop_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0008_remove_avatar_user_id_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.ImageField(null=True, upload_to=shop_api.models.profile_avatar_directory_path, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_api.avatar'),
        ),
    ]
