# Generated by Django 4.2.1 on 2023-06-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0013_remove_avatar_user_avatar_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='alt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='categories/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='products', verbose_name='image'),
        ),
    ]
