# Generated by Django 4.2.1 on 2023-06-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0015_remove_category_alt_category_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, verbose_name='category'),
        ),
    ]
