# Generated by Django 4.2.1 on 2023-07-02 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0017_product_is_limited_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='src',
        ),
    ]
