# Generated by Django 4.2.1 on 2023-07-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0019_product_number_of_purchases'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_banner',
            field=models.BooleanField(default=False, verbose_name='on banner'),
        ),
    ]
