# Generated by Django 4.2.1 on 2023-07-14 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_api', '0021_product_fulldescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('deliveryType', models.CharField(default='free', max_length=20)),
                ('paymentType', models.CharField(default='online', max_length=20)),
                ('totalCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='accepted', max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('products', models.ManyToManyField(related_name='products', to='shop_api.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'order',
            },
        ),
    ]
