# Generated by Django 4.2.1 on 2023-07-17 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0022_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
