# Generated by Django 4.2.1 on 2023-07-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0025_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='totalCost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
