# Generated by Django 4.2.1 on 2023-07-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0026_alter_order_totalcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dateFrom',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dateTo',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='salePrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
