# Generated by Django 4.2.1 on 2023-07-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0028_alter_product_dateto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dateFrom',
            field=models.DateField(null=True),
        ),
    ]
